import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/ui_self/Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#FFFFF0]/70 dark:bg-black min-h-screen flex flex-col overflow-y-auto`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
